services:
  postgres:
    image: postgres:17
    container_name: postgres_dev
    environment:
      POSTGRES_USER: timerecorder
      POSTGRES_PASSWORD: timerecorder
      POSTGRES_DB: timerecorder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
