services:
  postgres:
    image: postgres:17
    container_name: postgres_dev
    environment:
      POSTGRES_USER: miniverso
      POSTGRES_PASSWORD: miniverso
      POSTGRES_DB: miniverso
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
