allowBuilds:
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.2.6
  vitest: ^4.1.10
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - '@better-auth-ui/core@1.6.37'
  - '@better-auth-ui/react@1.6.37'
