services:
  miniverso:
    image: notkamui/miniverso:latest
    container_name: miniverso
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgres://miniverso:miniverso@localhost:5432/miniverso
      - SERVER_URL=https://miniverso.notkamui.com
    restart: unless-stopped
    networks:
      - miniverso

  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_USER=miniverso
      - POSTGRES_PASSWORD=miniverso
      - POSTGRES_DB=miniverso
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - miniverso

volumes:
  db_data:

networks:
  miniverso:
