/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as AccountPathnameRouteImport } from './routes/account/$pathname'
import { Route as AuthedTimeIndexRouteImport } from './routes/_authed/time/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedTimeStatsRouteImport } from './routes/_authed/time/stats'
import { Route as AuthedTimeDayRouteImport } from './routes/_authed/time/$day'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTimeIndexRoute = AuthedTimeIndexRouteImport.update({
  id: '/time/',
  path: '/time/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTimeStatsRoute = AuthedTimeStatsRouteImport.update({
  id: '/time/stats',
  path: '/time/stats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimeDayRoute = AuthedTimeDayRouteImport.update({
  id: '/time/$day',
  path: '/time/$day',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/time/$day': typeof AuthedTimeDayRoute
  '/time/stats': typeof AuthedTimeStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/time': typeof AuthedTimeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/time/$day': typeof AuthedTimeDayRoute
  '/time/stats': typeof AuthedTimeStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/time': typeof AuthedTimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/_authed/time/$day': typeof AuthedTimeDayRoute
  '/_authed/time/stats': typeof AuthedTimeStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/time/': typeof AuthedTimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/time/$day'
    | '/time/stats'
    | '/api/auth/$'
    | '/time'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/time/$day'
    | '/time/stats'
    | '/api/auth/$'
    | '/time'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/_authed/time/$day'
    | '/_authed/time/stats'
    | '/api/auth/$'
    | '/_authed/time/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AccountPathnameRoute: typeof AccountPathnameRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/time/': {
      id: '/_authed/time/'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthedTimeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/time/stats': {
      id: '/_authed/time/stats'
      path: '/time/stats'
      fullPath: '/time/stats'
      preLoaderRoute: typeof AuthedTimeStatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/time/$day': {
      id: '/_authed/time/$day'
      path: '/time/$day'
      fullPath: '/time/$day'
      preLoaderRoute: typeof AuthedTimeDayRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedTimeDayRoute: typeof AuthedTimeDayRoute
  AuthedTimeStatsRoute: typeof AuthedTimeStatsRoute
  AuthedTimeIndexRoute: typeof AuthedTimeIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTimeDayRoute: AuthedTimeDayRoute,
  AuthedTimeStatsRoute: AuthedTimeStatsRoute,
  AuthedTimeIndexRoute: AuthedTimeIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AccountPathnameRoute: AccountPathnameRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
