/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as AccountPathnameRouteImport } from './routes/account/$pathname'
import { Route as AuthedTimeRouteRouteImport } from './routes/_authed/time/route'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedTimeChar123DayChar125RouteImport } from './routes/_authed/time/{-$day}'
import { Route as AuthedTimeStatsRouteImport } from './routes/_authed/time/stats'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTimeRouteRoute = AuthedTimeRouteRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTimeChar123DayChar125Route =
  AuthedTimeChar123DayChar125RouteImport.update({
    id: '/{-$day}',
    path: '/{-$day}',
    getParentRoute: () => AuthedTimeRouteRoute,
  } as any)
const AuthedTimeStatsRoute = AuthedTimeStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthedTimeRouteRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/time': typeof AuthedTimeRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/time/stats': typeof AuthedTimeStatsRoute
  '/time/{-$day}': typeof AuthedTimeChar123DayChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/time': typeof AuthedTimeRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/time/stats': typeof AuthedTimeStatsRoute
  '/time/{-$day}': typeof AuthedTimeChar123DayChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/time': typeof AuthedTimeRouteRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/time/stats': typeof AuthedTimeStatsRoute
  '/_authed/time/{-$day}': typeof AuthedTimeChar123DayChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/time'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/admin/users'
    | '/time/stats'
    | '/time/{-$day}'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/time'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/admin/users'
    | '/time/stats'
    | '/time/{-$day}'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/admin'
    | '/_authed/time'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/_authed/admin/users'
    | '/_authed/time/stats'
    | '/_authed/time/{-$day}'
    | '/api/auth/$'
    | '/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AccountPathnameRoute: typeof AccountPathnameRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/time': {
      id: '/_authed/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthedTimeRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/time/{-$day}': {
      id: '/_authed/time/{-$day}'
      path: '/{-$day}'
      fullPath: '/time/{-$day}'
      preLoaderRoute: typeof AuthedTimeChar123DayChar125RouteImport
      parentRoute: typeof AuthedTimeRouteRoute
    }
    '/_authed/time/stats': {
      id: '/_authed/time/stats'
      path: '/stats'
      fullPath: '/time/stats'
      preLoaderRoute: typeof AuthedTimeStatsRouteImport
      parentRoute: typeof AuthedTimeRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedTimeRouteRouteChildren {
  AuthedTimeStatsRoute: typeof AuthedTimeStatsRoute
  AuthedTimeChar123DayChar125Route: typeof AuthedTimeChar123DayChar125Route
}

const AuthedTimeRouteRouteChildren: AuthedTimeRouteRouteChildren = {
  AuthedTimeStatsRoute: AuthedTimeStatsRoute,
  AuthedTimeChar123DayChar125Route: AuthedTimeChar123DayChar125Route,
}

const AuthedTimeRouteRouteWithChildren = AuthedTimeRouteRoute._addFileChildren(
  AuthedTimeRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedTimeRouteRoute: typeof AuthedTimeRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedTimeRouteRoute: AuthedTimeRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AccountPathnameRoute: AccountPathnameRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
