name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  type-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-toolchain
      - name: Run type check
        run: bun type-check

  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-toolchain
      - name: Run lint
        run: bun -b lint

  fmt:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-toolchain
      - name: Run fmt
        run: npx oxfmt --check

  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-toolchain
      - name: Run tests
        run: bun test:run
